#!/usr/bin/env bash
# Cloudflare IP 대역만 443 으로 들어올 수 있게 ufw 규칙을 갱신하고,
# nginx 가 CF-Connecting-IP 로 실제 클라이언트 IP 를 복원할 수 있게 real_ip 설정을 생성한다.
#
# 사용: sudo bash deploy/cloudflare-allowlist.sh
# Cloudflare 대역은 가끔 바뀌므로 cron 으로 주기 실행을 권장 (setup.sh 가 주 1회 cron 을 등록함).
#
# [방어] 공격자가 GCP 대역을 스캔해 origin IP 를 찾아내도, Cloudflare 를 거치지 않은 직접 접속은 방화벽에서 거부된다.
#        Cloudflare WAF/rate limit 을 우회하는 경로를 막는 핵심 설정.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "root 로 실행하세요 (sudo)" >&2
  exit 1
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4 -o "$TMP/v4"
curl -fsS --max-time 15 https://www.cloudflare.com/ips-v6 -o "$TMP/v6"

# 내려받은 목록이 비정상적으로 짧으면 중단 (빈 목록으로 규칙을 갈아엎는 사고 방지)
if [[ $(wc -l < "$TMP/v4") -lt 10 || $(wc -l < "$TMP/v6") -lt 3 ]]; then
  echo "Cloudflare IP 목록이 비정상입니다. 중단합니다." >&2
  exit 1
fi

# ---- ufw: 기존 cloudflare 규칙 제거 후 재등록 ----
# ufw 는 comment 기준 삭제가 없으므로 번호 목록을 역순으로 지운다
while read -r num; do
  yes | ufw delete "$num" >/dev/null
done < <(ufw status numbered | grep -F '# cloudflare' | sed -E 's/^\[ *([0-9]+)\].*/\1/' | sort -rn)

while read -r cidr; do
  [[ -z "$cidr" ]] && continue
  ufw allow proto tcp from "$cidr" to any port 443 comment cloudflare >/dev/null
done < <(cat "$TMP/v4" "$TMP/v6")

# ---- nginx real_ip ----
{
  echo "# generated by deploy/cloudflare-allowlist.sh on $(date -u +%FT%TZ)"
  while read -r cidr; do
    [[ -z "$cidr" ]] && continue
    echo "set_real_ip_from $cidr;"
  done < <(cat "$TMP/v4" "$TMP/v6")
  echo "real_ip_header CF-Connecting-IP;"
} > /etc/nginx/cloudflare-realip.conf

if command -v nginx >/dev/null && nginx -t >/dev/null 2>&1; then
  systemctl reload nginx
fi

echo "ufw 443 허용 대역: $(cat "$TMP/v4" "$TMP/v6" | wc -l) 개 (Cloudflare 만)"
echo "nginx real_ip 설정 갱신: /etc/nginx/cloudflare-realip.conf"
